# Generated by Django 5.1.3 on 2024-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=200)),
            ],
        ),
    ]
