# Generated by Django 5.1.3 on 2024-12-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
